BaseUrl= "http://donker008.github.io/"
LanguageCode= "en-us"
Title= "LiveCollage"
paginate = 5
DisqusShortname = "livecollage"
Copyright = "All rights reserved - 2016"
canonifyurls = true
theme = "casper"

[[menu.main]]
  name = "Home"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "About us"
  weight = -110
  identifier = "about"
  url = "/about"
 
 [[menu.main]]
  name = "App Privacy Policy"
  weight = -110
  identifier = "privacy"
  url = "/privacy" 

[params]
  description = "Instant Collage Maker"
  cover = "img/cover.jpg"
  author = "click2mobile"
  authorlocation = "..."
  authorwebsite = "http://livecollage.cc"
  bio= ""
  logo = "img/home.png"
  googleAnalyticsUserID = "UA-77935311-1"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/..." 

  twitterName = "livecollage"
  facebookName = "livecollage"
 
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
