BaseUrl= "http://example.com/"
LanguageCode= "EN-us"
Title= "LiveCollage"
paginate = 3
DisqusShortname = "livecollage"
Copyright = "All rights reserved - 2015"
canonifyurls = true
theme = "casper"

[[menu.main]]
  name = "LiveCollage"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "About us"
  weight = -110
  identifier = "about"
  url = "/about"
  

[params]
  description = "Instant Collage Maker"
  cover = "img/cover.jpg"
  author = "click2mobile"
  authorlocation = "..."
  authorwebsite = "http://livecollage.cc"
  bio= ""
  logo = "img/home.png"
  googleAnalyticsUserID = "UA-my"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/..." 

  twitterName = "livecollage"
  facebookName = "livecollage"
 
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
